#!/usr/bin/env bash

#****************************************************************************************************#
#                                        GUARDIAN FUNCTIONS                                          #
#****************************************************************************************************#

#-----------------------------------------------------------------------------------------------------
# CASTING YOUR VOTES TO YOUR PRODUCER
#-----------------------------------------------------------------------------------------------------

voteproducer() {

printf "\n[********************* CASTING VOTE TO BLOCK PRODUCER **********************]\n\n"

while [ : ]
do
          read -p "ENTER THE BLOCK PRODUCER TO CAST VOTES: " produceraccountnames

	  if [[ "$produceraccountnames" =~ [[:upper:]] ]]; then
		printf "\nERROR: ACCOUNT NAMES SHOULDN'T CONTAIN ANY CAPS.\n\n"
                continue

        elif [[ "${produceraccountnames//[a-z1-5]}" ]]; then
                printf "\nERROR: ACCOUNT NAMES SHOULD ONLY HAVE CHARACTERS BETWEEN [a-z] AND [1-5].\n\n"
                continue

	elif [[ "$owneraccountname" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: ACCOUNT NAMES SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

remcli system voteproducer prods $owneraccountname $produceraccountnames -p $owneraccountname@vote

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# CHECKING FOR USERS REMNODE ACCOUNT
#-----------------------------------------------------------------------------------------------------

newaccount() {

printf "\n"
read -p "ENTER YOUR ETHEREUM NODE ADDRESS: " ethnodeaddress
printf "\n"

read -p "ENTER YOUR CRYPTOCOMPARE API KEY: " cryptocomparekey
printf "\n"

while [ : ]
do
          read -p "ENTER YOUR TELEGRAM PUBLIC KEY: " telegrampublickey

	  if [[ ! "$telegrampublickey" = "${telegrampublickey%[[:space:]]*}" ]]; then
		printf "\nERROR: PUBLIC KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#telegrampublickey} -ne 53 ]]; then
                printf "\nERROR: PUBLIC KEY SHOULD ONLY BE 53 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$telegrampublickey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PUBLIC KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

while [ : ]
do
          read -p "ENTER YOUR TELEGRAM PRIVATE KEY: " telegramprivatekey

	  if [[ ! "$telegramprivatekey" = "${telegramprivatekey%[[:space:]]*}" ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#telegramprivatekey} -ne 51 ]]; then
                printf "\nERROR: PRIVATE KEY SHOULD ONLY BE 51 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$telegramprivatekey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

while [ : ]
do
          read -p "ENTER YOUR TELEGRAM ACCOUNT NAME: " telegramaccountname

	  if [[ "$telegramaccountname" =~ [[:upper:]] ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY CAPS.\n\n"
                continue

	elif [[ ! "$telegramaccountname" = "${telegramaccountname%[[:space:]]*}" ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ "${telegramaccountname//[a-z1-5]}" ]]; then
                printf "\nERROR: ACCOUNT NAME SHOULD ONLY HAVE CHARACTERS BETWEEN [a-z] AND [1-5].\n\n"
                continue

        elif [[ ${#telegramaccountname} -ne 12 ]]; then
                printf "\nERROR: ACCOUNT NAME SHOULD ONLY BE 12 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$telegramaccountname" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

while [ : ]
do
          read -p "ENTER YOUR NEW OWNER ACCOUNT NAME: " owneraccountname

	  if [[ "$owneraccountname" =~ [[:upper:]] ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY CAPS.\n\n"
                continue

	elif [[ ! "$owneraccountname" = "${owneraccountname%[[:space:]]*}" ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ "${owneraccountname//[a-z1-5]}" ]]; then
                printf "\nERROR: ACCOUNT NAME SHOULD ONLY HAVE CHARACTERS BETWEEN [a-z] AND [1-5].\n\n"
                continue

        elif [[ ${#owneraccountname} -ne 12 ]]; then
                printf "\nERROR: ACCOUNT NAME SHOULD ONLY BE 12 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$owneraccountname" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

while [ : ]
do
          read -p "ENTER THE AMOUNT TO TRANSFER TO YOUR NEW OWNER ACCOUNT: " ownertransferamount

	  if [[ $ownertransferamount -lt 3000 ]]; then
		printf "\nERROR: TRANSFER AMOUNT SHOULDN'T BE LESS THEN 3000 REM.\n\n"
                continue

	elif [[ ! "$ownertransferamount" = "${ownertransferamount%[[:space:]]*}" ]]; then
		printf "\nERROR: TRANSFER AMOUNT SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ "${ownertransferamount//[0-9]}" ]]; then
                printf "\nERROR: TRANSFER AMOUNT SHOULD ONLY CONTAIN CHARACTERS BETWEEN [0-9].\n\n"
                continue

	elif [[ "$ownertransferamount" =~ ['!@#$%^&*()_+,.£'] ]]; then
		printf "\nERROR: TRANSFER AMOUNT SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

#-----------------------------------------------------------------------------------------------------

printf "\n"
remcli wallet import --private-key=$telegramprivatekey
printf "\n"
remcli create key --file key1
cp key1 ownerkeys
echo $owneraccountname >> key1
sudo -S sed -i "/^Private key: /s/Private key: //" key1 && sudo -S sed -i "/^Public key: /s/Public key: //" key1
ownerpublickey=$(head -n 2 key1 | tail -1)
ownerprivatekey=$(head -n 1 key1 | tail -1)
remcli wallet import --private-key=$ownerprivatekey

printf "\n[********************** TAKE NOTE OF YOUR OWNER KEYS ***********************]\n\n"

echo "Account Name:" $owneraccountname
cat ./ownerkeys
printf "\n"
read -p 'Press [Enter] key to continue...'

printf "\n[******************** CREATING YOUR NEW OWNER ACCOUNT **********************]\n\n"

remcli system newaccount $telegramaccountname $owneraccountname $ownerpublickey $ownerpublickey -x 120 --transfer --stake "1000.0000 REM" -p $telegramaccountname@owner
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"
remcli transfer $telegramaccountname $owneraccountname -x 120 "$ownertransferamount REM" -p $telegramaccountname@owner
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------

existingaccount() {

read -p "ENTER YOUR ETHEREUM NODE ADDRESS: " ethnodeaddress
printf "\n"

read -p "ENTER YOUR CRYPTOCOMPARE API KEY: " cryptocomparekey
printf "\n"

while [ : ]
do
          read -p "ENTER YOUR OWNER PUBLIC KEY: " ownerpublickey

	  if [[ ! "$ownerpublickey" = "${ownerpublickey%[[:space:]]*}" ]]; then
		printf "\nERROR: PUBLIC KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#ownerpublickey} -ne 53 ]]; then
                printf "\nERROR: PUBLIC KEY SHOULD ONLY BE 53 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$ownerpublickey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PUBLIC KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

echo $ownerpublickey >> key1
printf "\n"

while [ : ]
do
          read -p "ENTER YOUR OWNER PRIVATE KEY: " ownerprivatekey

	  if [[ ! "$ownerprivatekey" = "${ownerprivatekey%[[:space:]]*}" ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#ownerprivatekey} -ne 51 ]]; then
                printf "\nERROR: PRIVATE KEY SHOULD ONLY BE 51 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$ownerprivatekey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

echo $ownerprivatekey >> key1
printf "\n"

while [ : ]
do
          read -p "ENTER YOUR OWNER ACCOUNT NAME: " owneraccountname

	  if [[ "$owneraccountname" =~ [[:upper:]] ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY CAPS.\n\n"
                continue

	elif [[ ! "$owneraccountname" = "${owneraccountname%[[:space:]]*}" ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ "${owneraccountname//[a-z1-5]}" ]]; then
                printf "\nERROR: ACCOUNT NAME SHOULD ONLY HAVE CHARACTERS BETWEEN [a-z] AND [1-5].\n\n"
                continue

        elif [[ ${#owneraccountname} -ne 12 ]]; then
                printf "\nERROR: ACCOUNT NAME SHOULD ONLY BE 12 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$owneraccountname" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: ACCOUNT NAME SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

echo $owneraccountname >> key1
printf "\n"
remcli wallet unlock --password=$walletpass > /dev/null 2>&1
remcli wallet import --private-key=$ownerprivatekey

}

#-----------------------------------------------------------------------------------------------------
# IMPORTING EXISTING KEY PERMISSIONS
#-----------------------------------------------------------------------------------------------------

oldkeypermissions() {

while [ : ]
do
          read -p "ENTER YOUR GUARDIAN PUBLIC KEY: " guardianpublickey

	  if [[ ! "$guardianpublickey" = "${guardianpublickey%[[:space:]]*}" ]]; then
		printf "\nERROR: PUBLIC KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#guardianpublickey} -ne 53 ]]; then
                printf "\nERROR: PUBLIC KEY SHOULD ONLY BE 53 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$guardianpublickey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PUBLIC KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

while [ : ]
do
          read -p "ENTER YOUR GUARDIAN PRIVATE KEY: " guardianprivatekey

	  if [[ ! "$guardianprivatekey" = "${guardianprivatekey%[[:space:]]*}" ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#guardianprivatekey} -ne 51 ]]; then
                printf "\nERROR: PRIVATE KEY SHOULD ONLY BE 51 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$guardianprivatekey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

remcli wallet unlock --password=$walletpass > /dev/null 2>&1
remcli wallet import --private-key=$guardianprivatekey

printf "\n"

while [ : ]
do
          read -p "ENTER YOUR TRANSFER PRIVATE KEY: " transferprivatekey

	  if [[ ! "$transferprivatekey" = "${transferprivatekey%[[:space:]]*}" ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#transferprivatekey} -ne 51 ]]; then
                printf "\nERROR: PRIVATE KEY SHOULD ONLY BE 51 CHARACTERS LONG.\n\n"
                continue

	elif [[ "$transferprivatekey" =~ ['!@#$%^&*()_+'] ]]; then
		printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

printf "\n"

remcli wallet import --private-key=$transferprivatekey
echo -e "\n\nplugin = eosio::producer_plugin\n\nplugin = eosio::producer_api_plugin\n\nproducer-name = $owneraccountname\n\nsignature-provider = $guardianpublickey=KEY:$guardianprivatekey\n\nplugin = eosio::eth_swap_plugin\n\nswap-authority = $owneraccountname@swap\n\nswap-signing-key = $guardianprivatekey\n\neth-wss-provider = $ethnodeaddress\n\neth_swap_contract_address=0x39882ab5105b1d627e6aed3ff39c1b004a18e207\n\nreturn_chain_id=ethropsten\n\nplugin = eosio::rem_oracle_plugin\n\ncryptocompare-apikey = $cryptocomparekey\n\noracle-authority = $owneraccountname@oracle\n\noracle-signing-key = $guardianprivatekey" >> ./config/config.ini
printf "\n"
voteproducer
printf "\n"
remcli wallet remove_key $ownerpublickey --password=$walletpass
printf "\n"
rm walletpass guardiansetup guardianwalletpass
printf "\n[******************************* COMPLETED *********************************]\n\n\n"

}

#-----------------------------------------------------------------------------------------------------
# GENERATING RANDOM ACTIVE ACCOUNT NAMES
#-----------------------------------------------------------------------------------------------------

newkeypermissions() {

owneraccountname=$(head -n 3 key1 | tail -1)
activeproducername1=a$(cat /dev/urandom | tr -dc 'a-z1-5' | fold -w 11 | head -n 1 |  grep -o . | sort |tr -d "\n")
activeproducername2=b$(cat /dev/urandom | tr -dc 'a-z1-5' | fold -w 11 | head -n 1 |  grep -o . | sort |tr -d "\n")
activeproducername3=c$(cat /dev/urandom | tr -dc 'a-z1-5' | fold -w 11 | head -n 1 |  grep -o . | sort |tr -d "\n")

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR REMNODE ACTIVE KEY 1
#-----------------------------------------------------------------------------------------------------

remcli create key --file key2
cp key2 activekeys1
sudo -S sed -i "/^Private key: /s/Private key: //" key2 && sudo -S sed -i "/^Public key: /s/Public key: //" key2
activepublickey1=$(head -n 2 key2 | tail -1)
activeprivatekey1=$(head -n 1 key2 | tail -1)
remcli wallet import --private-key=$activeprivatekey1
printf "\n[********************* TAKE NOTE OF YOUR ACTIVE KEY 1 **********************]\n\n"
echo "Account Name:" $activeproducername1
cat ./activekeys1
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR REMNODE ACTIVE KEY 2
#-----------------------------------------------------------------------------------------------------

remcli create key --file key3
cp key3 activekeys2
sudo -S sed -i "/^Private key: /s/Private key: //" key3 && sudo -S sed -i "/^Public key: /s/Public key: //" key3
activepublickey2=$(head -n 2 key3 | tail -1)
activeprivatekey2=$(head -n 1 key3 | tail -1)
remcli wallet import --private-key=$activeprivatekey2
printf "\n[********************* TAKE NOTE OF YOUR ACTIVE KEY 2 **********************]\n\n"
echo "Account Name:" $activeproducername2
cat ./activekeys2
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR REMNODE ACTIVE KEY 3
#-----------------------------------------------------------------------------------------------------

remcli create key --file key4
cp key4 activekeys3
sudo -S sed -i "/^Private key: /s/Private key: //" key4 && sudo -S sed -i "/^Public key: /s/Public key: //" key4
activepublickey3=$(head -n 2 key4 | tail -1)
activeprivatekey3=$(head -n 1 key4 | tail -1)
remcli wallet import --private-key=$activeprivatekey3
printf "\n[********************* TAKE NOTE OF YOUR ACTIVE KEY 3 **********************]\n\n"
echo "Account Name:" $activeproducername3
cat ./activekeys3
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR REMNODE GUARDIAN KEY
#-----------------------------------------------------------------------------------------------------

remcli create key --file key5
cp key5 guardiankeys
sudo -S sed -i "/^Private key: /s/Private key: //" key5 && sudo -S sed -i "/^Public key: /s/Public key: //" key5
guardianpublickey=$(head -n 2 key5 | tail -1)
guardianprivatekey=$(head -n 1 key5 | tail -1)
remcli wallet import --private-key=$guardianprivatekey
echo -e "\n\nplugin = eosio::producer_plugin\n\nplugin = eosio::producer_api_plugin\n\nproducer-name = $owneraccountname\n\nsignature-provider = $guardianpublickey=KEY:$guardianprivatekey\n\nplugin = eosio::eth_swap_plugin\n\nswap-authority = $owneraccountname@swap\n\nswap-signing-key = $guardianprivatekey\n\neth-wss-provider = $ethnodeaddress\n\neth_swap_contract_address=0x39882ab5105b1d627e6aed3ff39c1b004a18e207\n\nreturn_chain_id=ethropsten\n\nplugin = eosio::rem_oracle_plugin\n\ncryptocompare-apikey = $cryptocomparekey\n\noracle-authority = $owneraccountname@oracle\n\noracle-signing-key = $guardianprivatekey" >> ./config/config.ini
printf "\n[********************* TAKE NOTE OF YOUR GUARDIAN KEYS **********************]\n\n"
cat ./guardiankeys
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR REMNODE TRANSFER KEY
#-----------------------------------------------------------------------------------------------------

remcli create key --file key6
cp key6 transferkeys
sudo -S sed -i "/^Private key: /s/Private key: //" key6 && sudo -S sed -i "/^Public key: /s/Public key: //" key6
transferpublickey=$(head -n 2 key6 | tail -1)
transferprivatekey=$(head -n 1 key6 | tail -1)
remcli wallet import --private-key=$transferprivatekey
printf "\n[******************** TAKE NOTE OF YOUR TRANSFER KEYS **********************]\n\n"
cat ./transferkeys
printf "\n"
read -p 'Press [Enter] key to continue...'

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR REMCHAIN ACCOUNTS
#-----------------------------------------------------------------------------------------------------

printf "\n[*********************** CREATING ACTIVE ACCOUNT 1 *************************]\n\n"
remcli system newaccount $owneraccountname $activeproducername1 $activepublickey1 $activepublickey1 -x 120 --transfer --stake "1000.0000 REM" -p $owneraccountname@owner
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n[*********************** CREATING ACTIVE ACCOUNT 2 *************************]\n\n"
remcli system newaccount $owneraccountname $activeproducername2 $activepublickey2 $activepublickey2 -x 120 --transfer --stake "1000.0000 REM" -p $owneraccountname@owner
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n[*********************** CREATING ACTIVE ACCOUNT 3 *************************]\n\n"
remcli system newaccount $owneraccountname $activeproducername3 $activepublickey3 $activepublickey3 -x 120 --transfer --stake "1000.0000 REM" -p $owneraccountname@owner

#-----------------------------------------------------------------------------------------------------
# WAITING 2 MINUTES FOR TRANSCATION CONFIRMATION
#-----------------------------------------------------------------------------------------------------

DELAY=160
ELAPSED=0
REMAINING=0
CTR=0
STEP=3

printf "\n\n"

while [[ "${DELAY}" -ge "${ELAPSED}" ]]
do
	CTR=$(($CTR+1))
	REMAINING=$(($DELAY - $ELAPSED))
	MINS=$(($REMAINING/60))
	SECS=$(($REMAINING - ($MINS*60)))
	STEPSECS=$(($SECS - $STEP))

	if [[ ! $STEPSECS -ge 0 ]]
	then
		STEPSECS=0
	fi

	echo -ne " | Please wait for $MINS minutes $STEPSECS seconds ...\033[0K\r"

	for ((I=1;I<=$CTR;I++))
	do
		echo -ne ">"
	done

        sleep $STEP
	ELAPSED=$(($ELAPSED + $STEP))
done

printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# CREATING YOUR MULTISIG PERMISSIONS
#-----------------------------------------------------------------------------------------------------

setupmultisig() {

printf "\n\n[************************ CREATING ACTIVE MULTISIG *************************]\n\n"
remcli set account permission $owneraccountname active '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"'$activeproducername1'","permission":"active"},"weight":1},{"permission":{"actor":"'$activeproducername2'","permission":"active"},"weight":1},{"permission":{"actor":"'$activeproducername3'","permission":"active"},"weight":1}],"waits":[]}' owner -x 120 -p $owneraccountname@owner
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# CREATING REMCHAIN ACCOUNT PERMISSIONS
#-----------------------------------------------------------------------------------------------------

setupkeypermissions() {

printf "\n[********************** CREATING ACCOUNT PERMISSIONS ***********************]\n\n"

remcli set account permission $owneraccountname vote $guardianpublickey active -x 120 -p $owneraccountname@owner
remcli set account permission $owneraccountname safemode $ownerpublickey owner -x 120 -p $owneraccountname@owner
remcli set account permission $owneraccountname swap $transferpublickey active -x 120 -p $owneraccountname@owner
remcli set account permission $owneraccountname claim $guardianpublickey active -x 120 -p $owneraccountname@owner
remcli set account permission $owneraccountname stake $guardianpublickey active -x 120 -p $owneraccountname@owner
remcli set account permission $owneraccountname oracle $transferpublickey active -x 120 -p $owneraccountname@owner
remcli set account permission $owneraccountname transfer $transferpublickey active -x 120 -p $owneraccountname@owner

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# CREATING REMCHAIN ACTION PERMISSIONS 
#-----------------------------------------------------------------------------------------------------

createkeypermissions() {

printf "\n[*********************** CREATING ACTION PERMISSIONS ***********************]\n\n"

remcli set action permission $owneraccountname rem.swap init swap -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem delegatebw stake -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem voteproducer vote -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem claimrewards claim -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem unregprod safemode -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem regproducer safemode -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem.oracle setprice oracle -x 120 -p $owneraccountname@owner
remcli set action permission $owneraccountname rem.token transfer transfer -x 120 -p $owneraccountname@owner

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# SETTING YOUR STAKING AMOUNT
#-----------------------------------------------------------------------------------------------------

stakingamount() {

while [ : ]
do
          read -p "HOW MUCH WOULD YOU LIKE TO DELEGATE TOWARDS THE PRODUCER: " stakingamount

	  if [[ $stakingamount -lt 250000 ]]; then
		printf "\nERROR: DELEGATED AMOUNT SHOULDN'T BE LESS THEN 250000 REM.\n\n"
                continue

	elif [[ ! "$stakingamount" = "${stakingamount%[[:space:]]*}" ]]; then
		printf "\nERROR: DELEGATED AMOUNT SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ "${stakingamount//[0-9]}" ]]; then
                printf "\nERROR: DELEGATED AMOUNT SHOULD ONLY CONTAIN CHARACTERS BETWEEN [0-9].\n\n"
                continue

	elif [[ "$stakingamount" =~ ['!@#$%^&*()_+,.£'] ]]; then
		printf "\nERROR: DELEGATED AMOUNT SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

}

#-----------------------------------------------------------------------------------------------------
# DELEGATING STAKE TO YOUR GUARDIAN
#-----------------------------------------------------------------------------------------------------

stakingguardian() {

printf "\n\n[********************** DELEGATING STAKE TO GUARDIAN ***********************]\n\n"

remcli system delegatebw $owneraccountname $owneraccountname "$stakingamount REM" -x 120 -p $owneraccountname@stake

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# REGISTER AS A REMCHAIN GUARDIAN
#-----------------------------------------------------------------------------------------------------

registerguardian() {

printf "\n"

while [ : ]
do
	read -p "WOULD YOU LIKE TO REGISTER AS A GUARDIAN? [y/n]: " yn3

  	case $yn3 in
       		y|Y|yes|YES) echo ""
			     stakingamount
			     stakingguardian
			     voteproducer
	     		     break;;

       		n|N|no|NO)   break;;

       		*)   	     echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
  	esac
done

#-----------------------------------------------------------------------------------------------------
# REMOVING OWNER AND ACTIVE KEYS
#-----------------------------------------------------------------------------------------------------

printf "\n[********************* REMOVING OWNER AND ACTIVE KEYS **********************]\n\n"

remcli wallet remove_key $ownerpublickey --password=$walletpass
remcli wallet remove_key $activepublickey1 --password=$walletpass
remcli wallet remove_key $activepublickey2 --password=$walletpass
remcli wallet remove_key $activepublickey3 --password=$walletpass
remcli wallet remove_key $telegrampublickey --password=$walletpass

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# REBOOTING REMNODE AND FIXING ANY PROBLEMS
#-----------------------------------------------------------------------------------------------------

#sudo killall remnode
#sudo remnode --config-dir ./config/ --data-dir ./data/ --fix-reversible-blocks --force-all-checks --genesis-json genesis.json
#sudo remnode --config-dir ./config/ --data-dir ./data/ >> remnode.log 2>&1 &

#-----------------------------------------------------------------------------------------------------
# REMOVING FILES WHICH AINT REQUIRED ANYMORE
#-----------------------------------------------------------------------------------------------------

rm key1 key2 key3 key4 key5 key6 ownerkeys activekeys1 activekeys2 activekeys3 walletpass guardiankeys transferkeys guardiansetup guardianwalletpass

printf "\n[******************************* COMPLETED *********************************]\n\n\n"

}

#****************************************************************************************************#
#                                       GUARDIAN MAIN PROGRAM                                        #
#****************************************************************************************************#

#-----------------------------------------------------------------------------------------------------
# UPDATING AND UPGRADING PACKAGE DATABASE
#-----------------------------------------------------------------------------------------------------

sudo -S apt update && sudo -S apt upgrade -y
echo ""

#-----------------------------------------------------------------------------------------------------
# CHANGING DEFAULT SSH PORT NUMBER
#-----------------------------------------------------------------------------------------------------

while [ : ]
do

	 read -p "CHOOSE A RANDOM 5 DIGIT PORT NUMBER: " portnumber

         if [[ ${#portnumber} -ne 5 ]]
         then
                 printf "\nERROR: PORT NUMBER SHOULD BE EXACTLY 5 DIGITS.\n\n"
                 continue
         elif [[ ! -z "${portnumber//[0-9]}" ]]
         then
                 printf "\nERROR: PORT NUMBER SHOULD CONTAIN NUMBERS ONLY.\n\n"
                 continue
         else
                 sudo -S sed -i "/^#Port 22/s/#Port 22/Port $portnumber/" /etc/ssh/sshd_config && sed -i '/^PermitRootLogin/s/yes/without-password/' /etc/ssh/sshd_config && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
                 break
         fi
done

#-----------------------------------------------------------------------------------------------------
# INSTALLING UNCOMPLICATED FIREWALL
#-----------------------------------------------------------------------------------------------------

sudo -S apt-get install ufw -y
sudo -S ufw allow ssh/tcp
sudo -S ufw limit ssh/tcp
sudo -S ufw allow $portnumber/tcp
sudo -S ufw allow 8888/tcp
sudo -S ufw allow 9877/tcp
sudo -S ufw logging on
sudo -S ufw enable

#-----------------------------------------------------------------------------------------------------
# INSTALLING FAIL2BAN
#-----------------------------------------------------------------------------------------------------

sudo -S apt -y install fail2ban
sudo -S systemctl enable fail2ban
sudo -S systemctl start fail2ban
sudo -S service sshd restart

#-----------------------------------------------------------------------------------------------------
# INSTALLING CANONICAL LIVEPATCH SERVICE
#-----------------------------------------------------------------------------------------------------

sudo snap install canonical-livepatch

#-----------------------------------------------------------------------------------------------------
# INSTALLING REM PROTOCOL BINARIES
#-----------------------------------------------------------------------------------------------------

wget https://github.com/Remmeauth/remprotocol/releases/download/0.2.1/remprotocol_0.2.1-1_amd64.deb && sudo apt install ./remprotocol_0.2.1-1_amd64.deb

#-----------------------------------------------------------------------------------------------------
# BOOTING REMNODE AND WALLET
#-----------------------------------------------------------------------------------------------------

wget https://testchain.remme.io/genesis.json

#-----------------------------------------------------------------------------------------------------
# CREATING A CONFIG AND DATA DIRECTORIES
#-----------------------------------------------------------------------------------------------------

mkdir data && mkdir config

#-----------------------------------------------------------------------------------------------------
# CONFIGURATION FILE (CONFIG/CONFIG.INI)
#-----------------------------------------------------------------------------------------------------

echo -e "plugin = eosio::chain_api_plugin\n\nplugin = eosio::net_api_plugin\n\nhttp-server-address = 0.0.0.0:8888\n\np2p-listen-endpoint = 0.0.0.0:9876\n\n# https://remme.io\n\np2p-peer-address = p2p.testchain.remme.io:2087\n\n# https://eon.llc\n\np2p-peer-address = p2p.testnet.rem.eon.llc:9876\n\n# https://testnet.geordier.co.uk\n\np2p-peer-address = testnet.geordier.co.uk:9876\n\nverbose-http-errors = true\n\nchain-state-db-size-mb = 100480\n\nreversible-blocks-db-size-mb = 10480" > ./config/config.ini

#-----------------------------------------------------------------------------------------------------
# THE INITIAL RUN OF THE REMNODE
#-----------------------------------------------------------------------------------------------------

for ((i=1;i<=1;i++))
{
	remnode --config-dir /root/config/ --data-dir /root/data/ --delete-all-blocks --genesis-json /root/genesis.json 2>>/root/remnode.log &
	sleep 2
	echo ""
	break
}

while [ : ]
do
	systemdt=$(date '+%Y-%m-%dT%H:%M')
	
	if [ "$dt1" == "$systemdt" ]; then
		break
	else
		dt1=$(remcli get info | grep head_block_time | cut -c 23-38)
		dt1date=$(echo $dt1 | awk -F'T' '{print $1}' | awk -F'-' 'BEGIN {OFS="-"}{ print $3, $2, $1}')
		dt1time=$(echo $dt1 | awk -F'T' '{print $2}' | awk -F':' 'BEGIN {OFS=":"}{ print $1, $2}')

		dt2=$(tail -n 1 remnode.log | awk '{print $2}'| awk -F'.' '{print $1}')
		dt2date=$(echo $dt2 | awk -F'T' '{print $1}' | awk -F'-' 'BEGIN {OFS="-"}{ print $3, $2, $1}')
		dt2time=$(echo $dt2 | awk -F'T' '{print $2}' | awk -F':' 'BEGIN {OFS=":"}{ print $1, $2}')

		echo "Fetching blocks for [${dt1date} | ${dt1time}] | Current block date [${dt2date} | ${dt2time}]"
	fi

	echo ""
	sleep 2
done

#-----------------------------------------------------------------------------------------------------
# RUNNING THE WALLET DAEMON
#-----------------------------------------------------------------------------------------------------

remvault &
sleep 2

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# CREATING THE REMCLI WALLET
#-----------------------------------------------------------------------------------------------------

remcli wallet create --file walletpass
walletpass=$(cat walletpass)
echo $walletpass > guardianwalletpass

printf "\n"

#-----------------------------------------------------------------------------------------------------
# CREATING A NEW OWNER ACCOUNT
#-----------------------------------------------------------------------------------------------------

while [ : ]
do
	read -p "DO YOU WANT TO CREATE A NEW OWNER ACCOUNT? [y/n]: " yn1

  	case $yn1 in
       		y|Y|yes|YES) newaccount
	     		     break;;

       		n|N|no|NO)   existingaccount
       	     		     break;;

       		*)   	     echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
  	esac
done

#-----------------------------------------------------------------------------------------------------
# YOUR REMNODE WALLET PASSWORD
#-----------------------------------------------------------------------------------------------------

printf "\n[******************* TAKE NOTE OF YOUR WALLET PASSWORD *********************]\n\n"
cat ./walletpass
printf "\n"
echo " "
read -p 'Press [Enter] key to continue...'
printf "\n"

#-----------------------------------------------------------------------------------------------------
# CHECKING FOR EXISTING KEY PERMISSIONS
#-----------------------------------------------------------------------------------------------------

while [ : ]
do
	read -p "DO YOU HAVE EXISTING KEY PERMISSIONS? [y/n]: " yn2

  	case $yn2 in
       		y|Y|yes|YES) oldkeypermissions
	     		     break;;

       		n|N|no|NO)   newkeypermissions
			     setupmultisig
                             setupkeypermissions
                             createkeypermissions
                             registerguardian
       	     		     break;;

       		*)   	     echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
  	esac
done
