#!/usr/bin/env bash

#-----------------------------------------------------------------------------------------------------
# CREATING NEW SSH KEYS FOR SERVER
#-----------------------------------------------------------------------------------------------------

ssh_newkeys() {

printf "\n[********************* GENERATING YOUR NEW SSH KEYS ***********************]\n\n"
ssh-keygen -t rsa -b 4096

printf "\n[******************* TAKE NOTE OF YOUR SSH PRIVATE KEY *********************]\n\n"
sudo cat ~/.ssh/id_rsa
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# COPYING SSH KEY OVER TO THE LOCAL HOST
#-----------------------------------------------------------------------------------------------------

ssh_copy() {

printf "\n[*********************** TRANSFERING YOUR SSH KEYS *************************]\n\n"
read -p "PLEASE ENTER YOUR SERVER IP ADDRESS: " ssh_host_ipaddress
printf "\n"
ssh-copy-id -i ~/.ssh/id_rsa.pub root@$ssh_host_ipaddress

}

#-----------------------------------------------------------------------------------------------------
# WHILE LOOPS FOR SSH FUNCTIONS
#-----------------------------------------------------------------------------------------------------

while [ : ]
do
        read -p "DO YOU WANT TO GENERATE A NEW PAIR OF SSH KEYS? [y/n]: " yn1
    
        case $yn1 in
                y|Y|yes|YES) ssh_newkeys
                             break;;

                n|N|no|NO)   echo ""
                             break;;

                *)           echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
        esac
done

while [ : ]
do
        read -p "DO YOU WANT TO TRANSFER YOUR KEYS TO YOUR SERVER THROUGH SSH? [y/n]: " yn2
    
        case $yn2 in
                y|Y|yes|YES) ssh_copy
                             printf "\n[********************************** DONE ***********************************]\n\n"
                             break;;

                n|N|no|NO)   printf "\n[********************************** DONE ***********************************]\n\n"
                             break;;

                *)           echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
        esac
done
