#!/usr/bin/env bash

#-----------------------------------------------------------------------------------------------------
# CREATING NEW SSH KEYS FOR SERVER
#-----------------------------------------------------------------------------------------------------

ssh_newkeys() {

printf "\n\n[********************* GENERATING YOUR NEW SSH KEYS ***********************]\n\n"
printf "\n"
ssh-keygen -t rsa -b 4096

printf "\n\n[******************* TAKE NOTE OF YOUR SSH PRIVATE KEY *********************]\n\n"
printf "\n"
sudo cat ~/.ssh/id_rsa
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# COPYING SSH KEY OVER TO THE LOCAL HOST
#-----------------------------------------------------------------------------------------------------

ssh_copy() {

printf "\n\n[*********************** TRANSFERING YOUR SSH KEYS *************************]\n\n"
printf "\n"
read -p "PLEASE ENTER YOUR SERVER IP ADDRESS: " ssh_host_ipaddress
printf "\n"
ssh-keygen -f "/root/.ssh/known_hosts" -R "$ssh_host_ipaddress" > /dev/null 2>&1
ssh-copy-id -i ~/.ssh/id_rsa.pub root@$ssh_host_ipaddress

}

#-----------------------------------------------------------------------------------------------------
# WHILE LOOPS FOR SSH FUNCTIONS
#-----------------------------------------------------------------------------------------------------

printf "\n\n"

while [ : ]
do
        read -p "DO YOU WANT TO GENERATE A NEW PAIR OF SSH KEYS? [y/n]: " yn1

        case $yn1 in
                y|Y|yes|YES) ssh_newkeys
                             break;;

                n|N|no|NO)   echo ""
                             break;;

                *)           echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
        esac
done

while [ : ]
do
        read -p "DO YOU WANT TO TRANSFER YOUR KEYS TO YOUR SERVER THROUGH SSH? [y/n]: " yn2
    
        case $yn2 in
                y|Y|yes|YES) ssh_copy
                             printf "\n[********************************** DONE ***********************************]\n"
                             printf "\n"
                             break;;

                n|N|no|NO)   printf "\n[********************************** DONE ***********************************]\n"
                             printf "\n"
                             break;;

                *)           echo -e "\n\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
        esac
done
