#!/usr/bin/env bash

#-----------------------------------------------------------------------------------------------------
# CREATING NEW SSH KEYS FOR SERVER
#-----------------------------------------------------------------------------------------------------

ssh_newkeys() {

printf "\n[********************* GENERATING YOUR NEW SSH KEYS ***********************]\n\n"
su -c ssh-keygen

printf "\n[******************* TAKE NOTE OF YOUR SSH PRIVATE KEY *********************]\n\n"
sudo cat ~/.ssh/id_rsa
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"

}

#-----------------------------------------------------------------------------------------------------
# COPYING SSH KEY OVER TO THE LOCAL HOST
#-----------------------------------------------------------------------------------------------------

ssh_copy() {

sudo apt-get install sshpass -y
printf "\n[*********************** TRANSFERING YOUR SSH KEYS *************************]\n\n"
read -p "PLEASE ENTER YOUR LOCAL HOST PORT: " ssh_host_port
printf "\n"
read -p "PLEASE ENTER YOUR LOCAL IP ADDRESS: " ssh_host_ipaddress
printf "\n"
read -p "PLEASE ENTER YOUR LOCAL HOST USERNAME: " ssh_host_username
printf "\n"
read -p "PLEASE ENTER YOUR LOCAL HOST PASSWORD: " ssh_host_password
printf "\n"
sudo sshpass -p $ssh_host_password $ssh_host_port $ssh_host_username@$ssh_host_ipaddress "mkdir -p ~/.ssh"
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"
sudo sshpass -p $ssh_host_password ssh-copy-id $ssh_host_username@$ssh_host_ipaddress -p $ssh_host_port
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"
sudo sshpass -p $ssh_host_password $ssh_host_username@$ssh_host_ipaddress -p $ssh_host_port "sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config"
printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n"
sudo sshpass -p $ssh_host_password $ssh_host_username@$ssh_host_ipaddress -p $ssh_host_port "sudo systemctl restart ssh"

}

#-----------------------------------------------------------------------------------------------------
# WHILE LOOPS FOR SSH FUNCTIONS
#-----------------------------------------------------------------------------------------------------

while [ : ]
do
        read -p "DO YOU WANT TO GENERATE A NEW PAIR OF SSH KEYS? [y/n]: " yn1
    
        case $yn1 in
                y|Y|yes|YES) ssh_newkeys
                             break;;

                n|N|no|NO)   echo ""
                             break;;

                *)           echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
        esac
done

while [ : ]
do
        read -p "DO YOU WANT TO TRANSFER YOUR KEYS TO YOUR LOCAL HOST THROUGH SSH? [y/n]: " yn2
    
        case $yn2 in
                y|Y|yes|YES) ssh_copy
                             printf "\n[********************************** DONE ***********************************]\n\n"
                             break;;

                n|N|no|NO)   printf "\n[********************************** DONE ***********************************]\n\n"
                             break;;

                *)           echo -e "\nPLEASE ANSWER USING [y/n] or [Y/N]\n";;
        esac
done
